const clubIds = {
  j1: [
    { name: '札幌', id: 1 },
    { name: '仙台', id: 2 },
    { name: '鹿島', id: 3 },
    { name: '浦和', id: 4 },
    { name: '柏', id: 6 },
    { name: 'FC東京', id: 7 },
    { name: '川崎F', id: 8 },
    { name: '横浜FM', id: 9 },
    { name: '湘南', id: 26 },
    { name: '清水', id: 12 },
    { name: '磐田', id: 13 },
    { name: '名古屋', id: 29 },
    { name: 'G大阪', id: 14 },
    { name: 'C大阪', id: 15 },
    { name: '神戸', id: 16 },
    { name: '広島', id: 17 },
    { name: '鳥栖', id: 18 },
    { name: '長崎', id: 38 }
  ],
  j2: [
    { name: '山形', id: 19 },
    { name: '水戸', id: 20 },
    { name: '栃木', id: 44 },
    { name: '大宮', id: 5 },
    { name: '千葉', id: 22 },
    { name: '東京V', id: 23 },
    { name: '町田', id: 24 },
    { name: '横浜FC', id: 25 },
    { name: '甲府', id: 10 },
    { name: '松本', id: 27 },
    { name: '新潟', id: 11 },
    { name: '金沢', id: 28 },
    { name: '岐阜', id: 30 },
    { name: '京都', id: 31 },
    { name: '岡山', id: 32 },
    { name: '山口', id: 33 },
    { name: '讃岐', id: 34 },
    { name: '徳島', id: 35 },
    { name: '愛媛', id: 36 },
    { name: '福岡', id: 37 },
    { name: '熊本', id: 39 },
    { name: '大分', id: 40 }
  ],
  j3: [
    { name: '盛岡', id: 41 },
    { name: '秋田', id: 42 },
    { name: '福島', id: 43 },
    { name: '群馬', id: 21 },
    { name: 'YS横浜', id: 45 },
    { name: '相模原', id: 46 },
    { name: '長野', id: 47 },
    { name: '富山', id: 48 },
    { name: '藤枝', id: 49 },
    { name: '沼津', id: 50 },
    { name: '鳥取', id: 51 },
    { name: '北九州', id: 52 },
    { name: '鹿児島', id: 53 },
    { name: '琉球', id: 54 }
  ]
};

export default clubIds;